import { createContext, useContext, useState } from 'react';

export type Language = 'pt' | 'en' | 'es' | 'fr' | 'it' | 'ja' | 'zh' | 'ko' | 'ru' | 'tlh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Header
    about: "Sobre",
    projects: "Projetos", 
    technologies: "Tecnologias",
    yearsOfExperience: "Anos de Experiência",
    skills: "Skills",
    contact: "Contato",
    
    // Hero
    hello: "Olá, eu sou",
    subtitle: "Desenvolvedor Fullstack apaixonado por transformar ideias em soluções digitais",
    viewProjects: "Ver Projetos",
    contactButton: "Entre em Contato",
    downloadCV: "Baixar CV",
    
    // About
    me: "Mim",
    aboutTitle: "Desenvolvedor Fullstack",
    aboutDescription: "Desenvolvedor Fullstack com mais de 3 anos de experiência criando aplicações web modernas e escaláveis. Especializado em React, Node.js e tecnologias cloud, sempre buscando as melhores práticas e soluções inovadoras.",
    
    // Skills
    skillsTitle: "Minhas",
    frontend: "Frontend",
    backend: "Backend",
    databaseTools: "Database & Tools",
    
    // Projects
    projectsTitle: "Meus",
    ecommerceTitle: "E-commerce Platform",
    ecommerceDesc: "Plataforma completa de e-commerce com carrinho, pagamentos e painel administrativo.",
    taskAppTitle: "Task Management App",
    taskAppDesc: "Aplicativo de gerenciamento de tarefas com interface kanban e colaboração em tempo real.",
    dashboardTitle: "Analytics Dashboard",
    dashboardDesc: "Dashboard interativo para análise de dados com gráficos dinâmicos e relatórios em tempo real.",
    projectsDescription: "Alguns dos projetos que desenvolvi utilizando as mais modernas tecnologias",
    code: "Código",
    demo: "Demo",
    seeMoreProjects: "Ver Mais Projetos",

    // Contact
    contactFormTitle: "Formulário de Contato",
    contactInfoTitle: "Informações de Contato",
    contactTitle: "Entre em",
    contactSubtitle: "Contato",
    contactDescription: "Pronto para transformar sua ideia em realidade? Vamos conversar!",
    name: "Nome",
    email: "Email",
    phone: "Telefone",
    location: "Localização",
    message: "Mensagem",
    send: "Enviar Mensagem",
    socialLinksTitle: "Links Sociais",
    namePlaceholder: "Seu Nome Completo",
    emailPlaceholder: "Seu Email",
    messagePlaceholder: "Sua Mensagem",
    sendMessage: "Enviar Mensagem",
    messageSent: "Mensagem Enviada!",
    thankYou: "Obrigado por entrar em contato. Responderei o mais breve possível!",
    
    // Footer
    allRights: "Todos os direitos reservados.",
    quickLinks: "Links Rápidos",
    connect: "Conecte-se",
    footerDescription: "Desenvolvedor Fullstack criando soluções digitais inovadoras e experiências excepcionais."
  },
  
  en: {
    about: "About",
    projects: "Projects",
    technologies: "Technologies",
    yearsOfExperience: "Years of Experience",
    skills: "Skills", 
    contact: "Contact",
    hello: "Hello, I'm",
    subtitle: "Fullstack Developer passionate about transforming ideas into digital solutions",
    viewProjects: "View Projects",
    contactButton: "Contact Me",
    downloadCV: "Download CV",
    aboutTitle: "Fullstack Developer",
    me: "Me",
    aboutDescription: "Fullstack Developer with over 3 years of experience creating modern and scalable web applications. Specialized in React, Node.js and cloud technologies, always seeking best practices and innovative solutions.",
    skillsTitle: "My",
    frontend: "Frontend",
    backend: "Backend", 
    databaseTools: "Database & Tools",
    projectsTitle: "My",
    ecommerceTitle: "E-commerce Platform",
    ecommerceDesc: "Complete e-commerce platform with cart, payments and administrative panel.",
    taskAppTitle: "Task Management App",
    taskAppDesc: "Task management application with kanban interface and real-time collaboration.",
    dashboardTitle: "Analytics Dashboard",
    dashboardDesc: "Interactive dashboard for data analysis with dynamic charts and real-time reports.",
    projectsDescription: "Some of the projects I developed using the most modern technologies",
    code: "Code",
    demo: "Demo",
    seeMoreProjects: "See More Projects",
    contactTitle: "Get in",
    contactSubtitle: "Touch",
    contactDescription: "Ready to turn your idea into reality? Let's talk!",
    name: "Name",
    email: "Email",
    phone: "Phone",
    location: "Location",
    message: "Message",
    send: "Send Message",
    allRights: "All rights reserved.",
    contactInfoTitle: "Contact Information",
    socialLinksTitle: "Social Links",
    contactFormTitle: "Contact Form",
    namePlaceholder: "Your Full Name",
    emailPlaceholder: "Your Email",
    messagePlaceholder: "Your Message",
    sendMessage: "Send Message",
    messageSent: "Message Sent!",
    thankYou: "Thank you for contacting me. I will get back to you soon!",
    quickLinks: "Quick Links",
    connect: "Connect",
    madeWith: "Made with",
    technology: "technology",
    footerDescription: "Fullstack Developer creating innovative digital solutions and exceptional experiences."
  },
  
  es: {
    about: "Acerca",
    projects: "Proyectos",
    technologies: "Tecnologías",
    yearsOfExperience: "Años de Experiencia",
    skills: "Habilidades",
    contact: "Contacto",
    hello: "Hola, soy",
    subtitle: "Desarrollador Fullstack apasionado por transformar ideas en soluciones digitales",
    viewProjects: "Ver Proyectos",
    contactButton: "Contactar",
    downloadCV: "Descargar CV",
    aboutTitle: "Desarrollador Fullstack",
    me: "de Mí",
    aboutDescription: "Desarrollador Fullstack con más de 3 años de experiencia creando aplicaciones web modernas y escalables. Especializado en React, Node.js y tecnologías cloud, siempre buscando las mejores prácticas y soluciones innovadoras.",
    skillsTitle: "Mis",
    frontend: "Frontend",
    backend: "Backend",
    databaseTools: "Base de Datos y Herramientas",
    projectsTitle: "Mis",
    ecommerceTitle: "Plataforma E-commerce",
    ecommerceDesc: "Plataforma completa de e-commerce con carrito, pagos y panel administrativo.",
    taskAppTitle: "App de Gestión de Tareas",
    taskAppDesc: "Aplicación de gestión de tareas con interfaz kanban y colaboración en tiempo real.",
    dashboardTitle: "Dashboard de Analíticas",
    dashboardDesc: "Dashboard interactivo para análisis de datos con gráficos dinámicos e informes en tiempo real.",
    projectsDescription: "Algunos de los proyectos que desarrollé utilizando las tecnologías más modernas",
    code: "Código",
    demo: "Demo",
    seeMoreProjects: "Ver Más Proyectos",
    contactTitle: "Ponte en",
    contactSubtitle: "Contacto",
    contactDescription: "¿Listo para convertir tu idea en realidad? ¡Hablemos!",
    name: "Nombre",
    email: "Email",
    phone: "Teléfono",
    location: "Ubicación",
    message: "Mensaje",
    send: "Enviar Mensaje",
    allRights: "Todos los derechos reservados.",
    contactInfoTitle: "Información de Contacto",
    socialLinksTitle: "Enlaces Sociales",
    contactFormTitle: "Formulario de Contacto",
    namePlaceholder: "Tu Nombre Completo",
    emailPlaceholder: "Tu Email",
    messagePlaceholder: "Tu Mensaje",
    sendMessage: "Enviar Mensaje",
    messageSent: "Mensaje Enviado!",
    thankYou: "Gracias por contactarme. Me pondré en contacto contigo pronto!",
    quickLinks: "Enlaces Rápidos",
    connect: "Conecte-se",
    madeWith: "Hecho con",
    technology: "tecnología",
    footerDescription: "Desarrollador Fullstack creando soluciones digitales innovadoras y experiencias excepcionales."
  },
  
  fr: {
    about: "À propos",
    projects: "Projets",
    technologies: "Technologies",
    yearsOfExperience: "Years of Experience",
    skills: "Compétences",
    contact: "Contact",
    hello: "Bonjour, je suis",
    subtitle: "Développeur Fullstack passionné par la transformation d'idées en solutions digitales",
    viewProjects: "Voir les Projets",
    contactButton: "Contactez-moi",
    downloadCV: "Télécharger CV",
    aboutTitle: "Développeur Fullstack",
    me: "de Moi",
    aboutDescription: "Développeur Fullstack avec plus de 3 ans d'expérience dans la création d'applications web modernes et évolutives. Spécialisé en React, Node.js et technologies cloud, toujours à la recherche des meilleures pratiques et solutions innovantes.",
    skillsTitle: "Mes",
    frontend: "Frontend",
    backend: "Backend",
    databaseTools: "Base de Données et Outils",
    projectsTitle: "Mes",
    ecommerceTitle: "Plateforme E-commerce",
    ecommerceDesc: "Plateforme e-commerce complète avec panier, paiements et panneau administratif.",
    taskAppTitle: "App de Gestion de Tâches",
    taskAppDesc: "Application de gestion de tâches avec interface kanban et collaboration en temps réel.",
    dashboardTitle: "Tableau de Bord Analytique",
    dashboardDesc: "Tableau de bord interactif pour l'analyse de données avec graphiques dynamiques et rapports en temps réel.",
    projectsDescription: "Certains des projets que j'ai développés en utilisant les technologies les plus modernes",
    code: "Code",
    demo: "Demo",
    seeMoreProjects: "Voir Plus de Projets",
    contactTitle: "Entrer en",
    contactSubtitle: "Contact",
    contactDescription: "Prêt à transformer votre idée en réalité ? Parlons-en !",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    location: "Emplacement",
    message: "Message",
    send: "Envoyer le Message",
    allRights: "Tous droits réservés.",
    contactInfoTitle: "Informations de Contact",
    socialLinksTitle: "Liens Sociaux",
    contactFormTitle: "Formulaire de Contact",
    namePlaceholder: "Votre Nom Complet",
    emailPlaceholder: "Votre Email",
    messagePlaceholder: "Votre Message",
    sendMessage: "Envoyer le Message",
    messageSent: "Message Envoyé!",
    thankYou: "Merci de m'avoir contacté. Je vous recontacterai bientôt!",
    quickLinks: "Liens Rapides",
    connect: "Connexion",
    madeWith: "Fait avec",
    technology: "technologie",
    footerDescription: "Développeur Fullstack créant des solutions digitales innovantes et des expériences exceptionnelles."
  },
  
  it: {
    about: "Chi sono",
    projects: "Progetti",
    technologies: "Tecnologie",
    yearsOfExperience: "Anni di Esperienza",
    skills: "Competenze",
    contact: "Contatto",
    hello: "Ciao, sono",
    subtitle: "Sviluppatore Fullstack appassionato di trasformare idee in soluzioni digitali",
    viewProjects: "Vedi Progetti",
    contactButton: "Contattami",
    downloadCV: "Scarica CV",
    aboutTitle: "Sviluppatore Fullstack",
    me: "Sono",
    aboutDescription: "Sviluppatore Fullstack con oltre 3 anni di esperienza nella creazione di applicazioni web moderne e scalabili. Specializzato in React, Node.js e tecnologie cloud, sempre alla ricerca delle migliori pratiche e soluzioni innovative.",
    skillsTitle: "Le Mie",
    frontend: "Frontend",
    backend: "Backend",
    databaseTools: "Database e Strumenti",
    projectsTitle: "I Miei",
    ecommerceTitle: "Piattaforma E-commerce",
    ecommerceDesc: "Piattaforma e-commerce completa con carrello, pagamenti e pannello amministrativo.",
    taskAppTitle: "App di Gestione Attività",
    taskAppDesc: "Applicazione di gestione attività con interfaccia kanban e collaborazione in tempo reale.",
    dashboardTitle: "Dashboard Analytics",
    dashboardDesc: "Dashboard interattiva per l'analisi dei dati con grafici dinamici e report in tempo reale.",
    projectsDescription: "Alcuni dei progetti che ho sviluppato utilizzando le tecnologie più moderne",
    code: "Codice",
    demo: "Demo",
    seeMoreProjects: "Vedi Altri Progetti",
    contactTitle: "Mettiti in",
    contactSubtitle: "Contatto",
    contactDescription: "Pronto a trasformare la tua idea in realtà? Parliamone!",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    location: "Località",
    message: "Messaggio",
    send: "Invia Messaggio",
    allRights: "Tutti i diritti riservati.",
    contactInfoTitle: "Informazioni di Contatto",
    socialLinksTitle: "Link Sociali",
    contactFormTitle: "Formulario di Contatto",
    namePlaceholder: "Il Tuo Nome Completo",
    emailPlaceholder: "Il Tuo Email",
    messagePlaceholder: "Il Tuo Messaggio",
    sendMessage: "Invia Messaggio",
    messageSent: "Messaggio Inviato!",
    thankYou: "Grazie per avermi contattato. Ti risponderò presto!",
    quickLinks: "Link Rapidi",
    connect: "Connetti",
    madeWith: "Fatto con",
    technology: "tecnologia",
    footerDescription: "Sviluppatore Fullstack creando soluzioni digitali innovative e esperienze eccezionali."
  },
  
  ja: {
    about: "について",
    projects: "プロジェクト",
    technologies: "技術",
    yearsOfExperience: "経験年数",
    skills: "スキル",
    contact: "連絡先",
    hello: "こんにちは、私は",
    subtitle: "アイデアをデジタルソリューションに変えることに情熱を注ぐフルスタック開発者",
    viewProjects: "プロジェクトを見る",
    contactButton: "連絡先",
    downloadCV: "履歴書をダウンロード",
    aboutTitle: "フルスタック開発者",
    me: "について",
    aboutDescription: "モダンでスケーラブルなWebアプリケーションの作成に3年以上の経験を持つフルスタック開発者。React、Node.js、クラウド技術を専門とし、常にベストプラクティスと革新的なソリューションを追求しています。",
    skillsTitle: "私の",
    frontend: "フロントエンド",
    backend: "バックエンド",
    databaseTools: "データベース & ツール",
    projectsTitle: "私の",
    ecommerceTitle: "Eコマースプラットフォーム",
    ecommerceDesc: "カート、決済、管理パネルを備えた完全なeコマースプラットフォーム。",
    taskAppTitle: "タスク管理アプリ",
    taskAppDesc: "かんばんインターフェースとリアルタイムコラボレーションを備えたタスク管理アプリケーション。",
    dashboardTitle: "分析ダッシュボード",
    dashboardDesc: "動的グラフとリアルタイムレポートを備えたデータ分析用のインタラクティブダッシュボード。",
    projectsDescription: "動的グラフとリアルタイムレポートを備えたデータ分析用のインタラクティブダッシュボード。",
    code: "コード",
    demo: "デモ",
    seeMoreProjects: "もっとプロジェクトを見る",
    contactTitle: "お",
    contactSubtitle: "問い合わせ",
    contactDescription: "あなたのアイデアを現実に変える準備はできていますか？話しましょう！",
    name: "名前",
    email: "メール",
    phone: "電話",
    location: "場所",
    message: "メッセージ",
    send: "メッセージを送信",
    allRights: "全著作権所有。",
    contactInfoTitle: "連絡先情報",
    socialLinksTitle: "ソーシャルリンク",
    contactFormTitle: "連絡フォーム",
    namePlaceholder: "あなたの全名",
    emailPlaceholder: "あなたのメールアドレス",
    messagePlaceholder: "あなたのメッセージ",
    sendMessage: "メッセージを送信",
    messageSent: "メッセージが送信されました！",
    thankYou: "お問い合わせありがとうございます。すぐにご連絡いたします。",
    quickLinks: "クイックリンク",
    connect: "接続",
    madeWith: "作成",
    technology: "技術",
    footerDescription: "フルスタック開発者が革新的なデジタルソリューションと優れた体験を作成しています。"
  },
  
  zh: {
    about: "关于",
    projects: "项目",
    technologies: "技术",
    yearsOfExperience: "经验年数",
    skills: "技能",
    contact: "联系",
    hello: "你好，我是",
    subtitle: "热衷于将想法转化为数字解决方案的全栈开发者",
    viewProjects: "查看项目",
    contactButton: "联系我",
    downloadCV: "下载简历",
    aboutTitle: "全栈开发者",
    me: "我",
    aboutDescription: "拥有3年以上经验的全栈开发者，专注于创建现代可扩展的Web应用程序。专精React、Node.js和云技术，始终追求最佳实践和创新解决方案。",
    skillsTitle: "我的",
    frontend: "前端",
    backend: "后端",
    databaseTools: "数据库和工具",
    projectsTitle: "我的",
    ecommerceTitle: "电商平台",
    ecommerceDesc: "具有购物车、支付和管理面板的完整电商平台。",
    taskAppTitle: "任务管理应用",
    taskAppDesc: "具有看板界面和实时协作的任务管理应用程序。",
    dashboardTitle: "分析仪表板",
    dashboardDesc: "用于数据分析的交互式仪表板，具有动态图表和实时报告。",
    projectsDescription: "使用最现代技术开发的一些项目",
    code: "代码",
    demo: "演示",
    seeMoreProjects: "查看更多项目",
    contactTitle: "联系",
    contactSubtitle: "我",
    contactDescription: "准备好将您的想法变为现实吗？让我们谈谈！",
    name: "姓名",
    email: "邮箱",
    phone: "电话",
    location: "位置",
    message: "消息",
    send: "发送消息",
    allRights: "版权所有。",
    contactInfoTitle: "联系信息",
    socialLinksTitle: "社交链接",
    contactFormTitle: "联系表单",
    namePlaceholder: "您的全名",
    emailPlaceholder: "您的电子邮件",
    messagePlaceholder: "您的消息",
    sendMessage: "发送消息",
    messageSent: "消息已发送！",
    thankYou: "感谢您的联系。我会尽快回复您。",
    quickLinks: "快速链接",
    connect: "连接",
    madeWith: "使用",
    technology: "技术",
    footerDescription: "热衷于将想法转化为数字解决方案的全栈开发者。"
  },
  
  ko: {
    about: "소개",
    projects: "프로젝트",
    technologies: "기술",
    yearsOfExperience: "경험 년수",
    skills: "스킬",
    contact: "연락처",
    hello: "안녕하세요, 저는",
    subtitle: "아이디어를 디지털 솔루션으로 변환하는 것에 열정적인 풀스택 개발자",
    viewProjects: "프로젝트 보기",
    downloadCV: "이력서 다운로드",
    aboutTitle: "풀스택 개발자",
    aboutMe: "대해",
    aboutDescription: "현대적이고 확장 가능한 웹 애플리케이션 제작에 3년 이상의 경험을 가진 풀스택 개발자입니다. React, Node.js 및 클라우드 기술을 전문으로 하며, 항상 모범 사례와 혁신적인 솔루션을 추구합니다.",
    skillsTitle: "나의",
    frontend: "프론트엔드",
    backend: "백엔드",
    databaseTools: "데이터베이스 & 도구",
    projectsTitle: "나의",
    ecommerceTitle: "전자상거래 플랫폼",
    ecommerceDesc: "장바구니, 결제 및 관리 패널을 갖춘 완전한 전자상거래 플랫폼.",
    taskAppTitle: "작업 관리 앱",
    taskAppDesc: "칸반 인터페이스와 실시간 협업을 갖춘 작업 관리 애플리케이션.",
    dashboardTitle: "분석 대시보드",
    dashboardDesc: "동적 차트와 실시간 보고서를 갖춘 데이터 분석용 대화형 대시보드.",
    projectsDescription: "최신 기술을 사용하여 개발한 몇 가지 프로젝트",
    code: "코드",
    demo: "데모",
    seeMoreProjects: "더 많은 프로젝트 보기",
    contactTitle: "연락",
    contactSubtitle: "하기",
    contactDescription: "당신의 아이디어를 현실로 바꿀 준비가 되셨나요? 이야기해 봅시다!",
    name: "이름",
    email: "이메일",
    message: "메시지",
    send: "메시지 보내기",
    allRights: "모든 권리 보유.",
    contactInfoTitle: "연락처 정보",
    socialLinksTitle: "소셜 링크",
    contactFormTitle: "연락 양식",
    namePlaceholder: "전체 이름",
    emailPlaceholder: "이메일",
    messagePlaceholder: "메시지",
    sendMessage: "메시지 보내기",
    phone: "전화번호",
    location: "위치",
    messageSent: "메시지가 전송되었습니다!",
    thankYou: "연락을 남겨주셔서 감사합니다. 빠른 시일 내에 답변드리겠습니다.",
    quickLinks: "빠른 링크",
    connect: "연결",
    madeWith: "만들어짐",
    technology: "기술",
    footerDescription: "아이디어를 디지털 솔루션으로 변환하는 것에 열정적인 풀스택 개발자입니다."
  },
  
  ru: {
    about: "Обо мне",
    projects: "Проекты",
    technologies: "Технологии",
    yearsOfExperience: "Опыт работы",
    skills: "Навыки",
    contact: "Контакты",
    hello: "Привет, я",
    subtitle: "Fullstack разработчик, увлеченный превращением идей в цифровые решения",
    viewProjects: "Посмотреть проекты",
    downloadCV: "Скачать резюме",
    aboutTitle: "Fullstack разработчик",
    me: "мне",
    aboutDescription: "Fullstack разработчик с более чем 3-летним опытом создания современных и масштабируемых веб-приложений. Специализируюсь на React, Node.js и облачных технологиях, всегда стремлюсь к лучшим практикам и инновационным решениям.",
    skillsTitle: "Мои",
    frontend: "Фронтенд",
    backend: "Бэкенд",
    databaseTools: "База данных и инструменты",
    projectsTitle: "Мои",
    ecommerceTitle: "E-commerce платформа",
    ecommerceDesc: "Полная платформа электронной коммерции с корзиной, платежами и административной панелью.",
    taskAppTitle: "Приложение управления задачами",
    taskAppDesc: "Приложение для управления задачами с интерфейсом kanban и совместной работой в реальном времени.",
    dashboardTitle: "Аналитическая панель",
    dashboardDesc: "Интерактивная панель для анализа данных с динамическими графиками и отчетами в реальном времени.",
    projectsDescription: "Некоторые из проектов, разработанных с использованием самых современных технологий",
    code: "Код",
    demo: "Демо",
    seeMoreProjects: "Посмотреть больше проектов",
    contactTitle: "Связаться",
    contactSubtitle: "со мной",
    contactDescription: "Готовы превратить вашу идею в реальность? Давайте поговорим!",
    name: "Имя",
    email: "Email",
    message: "Сообщение",
    send: "Отправить сообщение",
    allRights: "Все права защищены.",
    contactInfoTitle: "Контактная информация",
    socialLinksTitle: "Социальные ссылки",
    contactFormTitle: "Форма контакта",
    namePlaceholder: "Ваше полное имя",
    emailPlaceholder: "Ваш email",
    messagePlaceholder: "Ваше сообщение",
    sendMessage: "Отправить сообщение",
    phone: "Телефон",
    location: "Местоположение",
    messageSent: "Сообщение отправлено!",
    thankYou: "Спасибо за ваше сообщение. Я свяжусь с вами в ближайшее время.",
    quickLinks: "Быстрые ссылки",
    connect: "Связаться",
    madeWith: "Сделан с",
    technology: "технология",
    footerDescription: "Fullstack разработчик, увлеченный превращением идей в цифровые решения."
  },
  
  tlh: {
    about: "jup",
    projects: "jup maH",
    technologies: "nugh",
    yearsOfExperience: "nugh",
    skills: "nugh",
    contact: "jup",
    hello: "nuqneH, jIH",
    subtitle: "naDev digital DIch chenmoH naQ chenmoH DIch",
    viewProjects: "maH legh",
    downloadCV: "nav teywI' naDev",
    aboutTitle: "naDev",
    me: "jIH",
    aboutDescription: "DIch chenmoHwI' DIch chenmoH nugh naDev chenmoH DIch. React, Node.js DIch lo'taHvIS, reD nugh DIch lo'taHvIS, nugh naDev DIch chenmoH.",
    skillsTitle: "jIj",
    frontend: "Frontend",
    backend: "Backend",
    databaseTools: "nugh malja' DIch",
    projectsTitle: "jIj",
    ecommerceTitle: "DIch maH nugh",
    ecommerceDesc: "DIch maH nugh DIch chenmoH DIch.",
    taskAppTitle: "DIch maH nugh",
    taskAppDesc: "DIch maH nugh kanban DIch chenmoH.",
    dashboardTitle: "DIch nugh malja'",
    dashboardDesc: "DIch nugh malja' DIch chenmoH DIch.",
    projectsDescription: "DIch nugh malja' DIch chenmoH DIch.",
    code: "nugh",
    demo: "cha'",
    seeMoreProjects: "law' maH legh",
    contactFormTitle: "DIch jup",
    phone: "DIch jup",
    location: "DIch jup",
    contactTitle: "jup",
    contactSubtitle: "DIch",
    contactDescription: "naDev chenmoH DIch? jatlhqa'!",
    name: "pagh",
    email: "nav",
    message: "nugh",
    send: "nugh naDev",
    allRights: "Hoch DIch.",
    contactInfoTitle: "DIch jup",
    socialLinksTitle: "DIch jup",
    namePlaceholder: "DIch jup",
    emailPlaceholder: "DIch jup",
    messagePlaceholder: "DIch jup",
    sendMessage: "DIch jup",
    messageSent: "DIch jup",
    thankYou: "DIch jup",
    quickLinks: "DIch jup",
    connect: "DIch jup",
    madeWith: "DIch jup",
    technology: "DIch jup",
    footerDescription: "DIch chenmoH naQ chenmoH DIch"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};